from typing import Dict
from app.schemas.port import PortSpec
from app.schemas.vessel import VesselSpec
from app.utils.port_congestion import get_port_congestion

# USD to INR Conversion Benchmark
USD_TO_INR_RATE: float = 83.5

# Vessel Multipliers relative to standard market index
VESSEL_RATE_MULTIPLIERS: Dict[str, float] = {
    "capesize": 0.82,
    "panamax": 0.96,
    "supramax": 1.12,
    "handysize": 1.30,
}

# -------------------------------------------------------------
# VESSEL SPECIFICATIONS (4 CLASSES)
# -------------------------------------------------------------
VESSEL_SPECS: Dict[str, VesselSpec] = {
    "capesize": VesselSpec(
        id="capesize",
        name="Capesize Bulk Carrier",
        category_name="Very Large Bulk Carrier",
        dwt_min=120000.0,
        dwt_max=210000.0,
        dwt_avg=180000.0,
        draft=18.2,
        loa=292.0,
        beam=45.0,
        speed=13.5,
        fuel_consumption=44.0,
        base_freight_rate=14.2,
        hourly_rate=1250.0,
        demurrage_rate_per_day=30000.0,
        availability="Limited",
        description="High-volume heavy bulk carrier optimal for deep-water berths (Dhamra). Extreme economies of scale for iron ore and metallurgical coking coal.",
    ),
    "panamax": VesselSpec(
        id="panamax",
        name="Kamsarmax / Panamax",
        category_name="Mid-Size Gearless",
        dwt_min=65000.0,
        dwt_max=85000.0,
        dwt_avg=82000.0,
        draft=14.2,
        loa=229.0,
        beam=32.26,
        speed=14.0,
        fuel_consumption=28.0,
        base_freight_rate=17.4,
        hourly_rate=850.0,
        demurrage_rate_per_day=20400.0,
        availability="Available",
        description="Workhorse dry-bulk bulker suited for Indian coastal terminals (Paradip & Vizag). Balanced parcel capacity with wide draft compatibility.",
    ),
    "supramax": VesselSpec(
        id="supramax",
        name="Ultramax / Supramax",
        category_name="Geared Handymax",
        dwt_min=52000.0,
        dwt_max=65000.0,
        dwt_avg=63500.0,
        draft=12.8,
        loa=199.9,
        beam=32.26,
        speed=14.2,
        fuel_consumption=24.0,
        base_freight_rate=20.2,
        hourly_rate=720.0,
        demurrage_rate_per_day=17280.0,
        availability="Available",
        description="Geared bulk carrier equipped with 4x30T deck cranes and grabs. High operational flexibility across all ports and lighterage anchorages.",
    ),
    "handysize": VesselSpec(
        id="handysize",
        name="Handysize Bulker",
        category_name="Small Coastal Geared",
        dwt_min=28000.0,
        dwt_max=40000.0,
        dwt_avg=38000.0,
        draft=10.2,
        loa=179.9,
        beam=28.4,
        speed=13.8,
        fuel_consumption=17.0,
        base_freight_rate=23.8,
        hourly_rate=520.0,
        demurrage_rate_per_day=12480.0,
        availability="Available",
        description="Shallow draft bulker uniquely capable of navigating Kolkata (SMP) lock dock system and Haldia river bar constraints without lighterage.",
    ),
}

# -------------------------------------------------------------
# PORT SPECIFICATIONS (5 EAST COAST INDIAN PORTS)
# Congestion computed dynamically from traffic history & capacity utilization
# -------------------------------------------------------------
PORT_SPECS: Dict[str, PortSpec] = {
    "Paradip": PortSpec(
        id="Paradip",
        name="Paradip Port Authority (PPA)",
        state="Odisha, India",
        coordinates=[20.2644, 86.6713],
        max_draft=16.5,
        max_loa=285.0,
        max_beam=48.0,
        congestion=get_port_congestion("Paradip"),
        berthing_wait_days=2.4,
        handling_rate_mt_per_day=38000.0,
        handling_rating=4.2,
        weather_risk="Medium",
        base_port_fee_usd=28200.0,
        cargo_handling_cost_per_mt=1.85,
        description="Deep-water multi-commodity port with mechanized iron ore & coal terminals. Capable of handling fully laden Panamax and partially lightened Capesize.",
    ),
    "Dhamra": PortSpec(
        id="Dhamra",
        name="Dhamra Port (Adani Ports)",
        state="Odisha, India",
        coordinates=[20.8122, 86.9603],
        max_draft=18.5,
        max_loa=310.0,
        max_beam=52.0,
        congestion=get_port_congestion("Dhamra"),
        berthing_wait_days=1.1,
        handling_rate_mt_per_day=55000.0,
        handling_rating=4.8,
        weather_risk="Low",
        base_port_fee_usd=34200.0,
        cargo_handling_cost_per_mt=1.60,
        description="Private all-weather deep-draft harbor with state-of-the-art automated conveyor loading. Accommodates fully laden Capesize up to 180k DWT.",
    ),
    "Vizag": PortSpec(
        id="Vizag",
        name="Visakhapatnam Port (VPA)",
        state="Andhra Pradesh, India",
        coordinates=[17.6868, 83.2185],
        max_draft=16.5,
        max_loa=280.0,
        max_beam=44.0,
        congestion=get_port_congestion("Vizag"),
        berthing_wait_days=2.9,
        handling_rate_mt_per_day=32000.0,
        handling_rating=4.0,
        weather_risk="Medium",
        base_port_fee_usd=26800.0,
        cargo_handling_cost_per_mt=2.10,
        description="Major natural land-locked outer harbour with dedicated mechanized general cargo and thermal coal berths. Excellent rail connectivity to central India steel plants.",
    ),
    "Haldia": PortSpec(
        id="Haldia",
        name="Haldia Dock Complex (HDC)",
        state="West Bengal, India",
        coordinates=[22.0227, 88.0583],
        max_draft=8.8,
        max_loa=195.0,
        max_beam=30.5,
        congestion=get_port_congestion("Haldia"),
        berthing_wait_days=5.2,
        handling_rate_mt_per_day=16500.0,
        handling_rating=3.2,
        weather_risk="Medium",
        base_port_fee_usd=22500.0,
        cargo_handling_cost_per_mt=2.65,
        description="Riverine tidal lock-gate dock system with seasonal Sandheads bar draft limits (8.8m). Requires river pilotage and Handysize or lightened Supramax parcels.",
    ),
    "Kolkata": PortSpec(
        id="Kolkata",
        name="Syama Prasad Mookerjee Port (Kolkata)",
        state="West Bengal, India (SMP Kolkata)",
        coordinates=[22.5411, 88.3186],
        max_draft=7.6,
        max_loa=172.0,
        max_beam=25.0,
        congestion=get_port_congestion("Kolkata"),
        berthing_wait_days=6.5,
        handling_rate_mt_per_day=10500.0,
        handling_rating=2.8,
        weather_risk="High",
        base_port_fee_usd=19800.0,
        cargo_handling_cost_per_mt=3.15,
        description="Historic river port on the Hooghly with sandbar draft constraints (Eden Channel 7.6m) and lock navigation. Suited strictly for parcel Handysize.",
    ),
}

# -------------------------------------------------------------
# ROUTE BASELINE SPOT RATES ($/MT)
# -------------------------------------------------------------
ROUTE_BASELINE_RATES: Dict[str, Dict[str, float]] = {
    "Australia": {
        "Paradip": 16.8,
        "Dhamra": 16.2,
        "Vizag": 16.5,
        "Haldia": 22.4,
        "Kolkata": 25.2,
    },
    "Indonesia": {
        "Paradip": 10.4,
        "Dhamra": 9.8,
        "Vizag": 9.6,
        "Haldia": 13.8,
        "Kolkata": 15.9,
    },
    "South Africa": {
        "Paradip": 17.5,
        "Dhamra": 17.0,
        "Vizag": 16.8,
        "Haldia": 22.8,
        "Kolkata": 25.6,
    },
    "Mozambique": {
        "Paradip": 15.8,
        "Dhamra": 15.3,
        "Vizag": 15.1,
        "Haldia": 20.9,
        "Kolkata": 23.8,
    },
    "Russia": {
        "Paradip": 34.5,
        "Dhamra": 33.8,
        "Vizag": 34.0,
        "Haldia": 40.5,
        "Kolkata": 43.8,
    },
}
